spring.application.name=gateway
server.port=8083

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true