spring.application.name=pagamentos-ms
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/food_pagamento
spring.datasource.username=postgres
spring.datasource.password=32213115
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.instance.prefer-ip-address=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs